**<font size="7">Análise das emoções de Relatórios Financeiros </font>**


**O Modelo 1 é apenas um teste que eu fiz em um único relatório, <mark>o Modelo 2 é código final.</mark>**

**OBS:** Os dados no dicionário de emoções estão desbalanceados.

# Carregar Bibliotecas

In [ ]:
#pip install -U sentence-transformers

In [ ]:
# OBS: Não consegui instalar no meu pc. Por isso, só consigo rodar este notebook no Google Colab
#pip install tf-keras

In [ ]:
#pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)

In [ ]:
from transformers import (
    AutoTokenizer,
    BertForSequenceClassification,
    pipeline,
)
import pandas as pd
import nltk
import re

# Baixar o modelo de segmentação de frases do NLTK
nltk.download('punkt') # Necessário para segmentação de sentenças
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize


from warnings import filterwarnings
filterwarnings('ignore') # remover avisos

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer

# Importar dados

In [ ]:
# Tabela com os relatórios
df = pd.read_excel("/content/Relatorio_Planilha_Analise_Sentimento1.xlsx")
print(f"Dimensões:{df.shape}")
df.head(3)

Dimensões:(50, 5)

,Id_Empresa,Nome,t-1,t,t+2
0,1,Petrobras,A Petróleo Brasileiro S.A. Petrobras dedicase...,A Petróleo Brasileiro S.A. - Petrobras dedica-...,"A Petróleo Brasileiro S.A. – Petrobras, Socied..."
1,2,Ambev,A Companhia de Bebidas das Américas – Ambev (r...,\nA Ambev S.A. (referida como “Companhia” ou “...,"A Ambev S.A. (referida como “Companhia”, “Ambe..."
2,3,Via S.A,"\n\nA Via Varejo S.A., diretamente ou por meio...","\n\nA Via Varejo S.A., diretamente ou por meio...","A Via S.A., diretamente ou por meio de suas co..."

### Dicionários de emoções
**OBS:** Os dados estão desbalanceados.

In [ ]:
# Dicionários de emoções
df_alegria=  pd.read_excel("dicionario_sentimentos_v3.0.xlsx", sheet_name=1)
df_medo = pd.read_excel("dicionario_sentimentos_v3.0.xlsx", sheet_name=2)
df_raiva = pd.read_excel("dicionario_sentimentos_v3.0.xlsx", sheet_name=3)
df_repugnancia = pd.read_excel("dicionario_sentimentos_v3.0.xlsx", sheet_name=4)
df_surpresa = pd.read_excel("/content/dicionario_sentimentos_v3.0.xlsx", sheet_name=5)
df_tristeza = pd.read_excel("/content/dicionario_sentimentos_v3.0.xlsx", sheet_name=6)

df_tristeza.head(3)

                Tristeza
0                Abdicar
1             Abaixo dos
2  padrões estabelecidos

In [ ]:
# Dimensões dos dicionários
print(f"Dimensões Alegria:{df_alegria.shape}")
print(f"Dimensões Medo:{df_medo.shape}")
print(f"Dimensões Raiva:{df_raiva.shape}")
print(f"Dimensões Repugnância:{df_repugnancia.shape}")
print(f"Dimensões Surpresa:{df_surpresa.shape}")

Dimensões Alegria:(302, 1)
Dimensões Medo:(158, 1)
Dimensões Raiva:(147, 1)
Dimensões Repugnância:(110, 1)
Dimensões Surpresa:(73, 1)

# Preparar dados

### Preparar dicionário

In [ ]:
# Transformar as emoções em lista
list_alegria = df_alegria['Alegria'].tolist()
list_medo = df_medo['Medo'].tolist()
list_raiva = df_raiva['Raiva'].tolist()
list_repugnancia = df_repugnancia['Repugnância'].tolist()
list_surpresa = df_surpresa['Surpresa'].tolist()
print(list_alegria ) # Exibir a lista "alegria"

['Abastança', 'Abono', 'Abrandar', 'Abrilhantar', 'Abundância', 'Acalmar', 'Acessível', 'Aclamado', 'Acolhedor', 'Adiantamento', 'Admirar', 'Afável', 'Completar', 'Compreensível', 'Conceder herança', 'Conciliação', 'Concluir', 'Concordar', 'Condecoração', 'Confiança', 'Congratulação', 'Conquista', 'Consagrado', 'Constância', 'Evolução', 'Excelência', 'Excepcional', 'Excitação', 'Executar', 'Êxito', 'Êxtase', 'Extraordinário', 'Fácil', 'Fantástico', 'Fartura', 'Favorável', 'Merecedor', 'Meritório', 'Momento de alta', 'Muito', 'Notável', 'Notório', 'Obtenção', 'Ocasião propícia', 'Oportunidade', 'Otimista', 'Ótimo', 'Ousadia', 'Rentável', 'Reparação', 'Representação de uma ideia', 'Reputação', 'Resolução', 'Respeito', 'Resultado positivo', 'Retidão', 'Retificação', 'Retribuição', 'Revogação', 'Revolucionar', 'Afirmativo', 'Afortunado', 'Agradável', 'Ajuda', 'Alcançar', 'Alegre', 'Alertar', 'Aliança', 'Alívio', 'Amável', 'Aperfeiçoar', 'Apoiar', 'Aprazível', 'Apreciável', 'Aprimorar', 'Apto', 'Aquisição', 'Aquisição', 'Assegurar', 'Atingir (objetivo)', 'Atitude', 'Atraente', 'Auxílio', 'Avanço', 'Baratear', 'Belo', 'Bem', 'Benéfico', 'Benemérito', 'Benfeitoria', 'Benigno', 'Boa reputação', 'Bom', 'Bondoso', 'Bonito', 'Brilhante', 'Brio', 'Calmo', 'Capaz', 'Caridade', 'Caridoso', 'Categórico', 'Cativante', 'Construtivo', 'Consulta', 'Contente', 'Convicção', 'Convincente', 'Cooperação', 'Cordial', 'Delicioso', 'Descoberta', 'Descobrir', 'Desejável', 'Desempenho superior', 'Desfrutar', 'Despreocupação', 'Destaque', 'Determinação', 'Devidamente', 'Digno', 'Diligente', 'Dinamismo', 'Disciplinar', 'Distinção', 'Diversão', 'Divulgar', 'Duradouro', 'Efetivo', 'Efetuar', 'Eficaz', 'Eficiência', 'Elevar', 'Elogio', 'Emoção', 'Emocionar', 'Empolgado', 'Encantado', 'Encorajar', 'Energético', 'Energia', 'Engrandecer', 'Entreter', 'Entusiasmo', 'Escalar', 'Esclarece', 'Favorito', 'Feliz', 'Fenomenal', 'Fidedigno', 'Fiel/fidelidade', 'Finalizar', 'Firme', 'Firmeza de', 'propósito', 'Folga', 'Força', 'Formidável', 'Formoso', 'Ganhar', 'Garantia', 'Genial', 'Gentil', 'Gracioso', 'Grande', 'Gratificação', 'Hábil', 'Homenagem', 'Honestidade', 'Honorável', 'Honra', 'Ideal', 'Ilustre', 'Imbatível', 'Imperioso', 'Importância', 'Incentivado', 'Incontestável', 'Incrível', 'Indenização', 'Influência', 'Informativo', 'Inovação', 'Instrutivo', 'Integridade', 'Inteireza', 'Intenso', 'Invencível', 'Justificável', 'Líder', 'Ovacionado', 'Parceria', 'Perdoar', 'Perfeição', 'Permissão', 'Perpétuo', 'Perseverança', 'Persistir', 'Perspicaz', 'Plano', 'Plenitude', 'Posicionar', 'Positivo', 'Possibilitar', 'Postura', 'Prazer', 'Preciso', 'Predileto', 'Predisposto', 'Prêmio', 'Prestígio', 'Pretensão', 'Prevenção', 'Proativo', 'Processar', 'Proeza', 'Professar (fé)', 'Proficiência', 'Progresso', 'Promoção cargo)', 'Propício', 'Prosperar', 'Prudência', 'Pulsante', 'Pureza', 'Qualificado', 'Querido', 'Realçar', 'Realização', 'Reaver', 'Receptivo', 'Recompensa', 'Recordação', 'Riqueza', 'Robustez', 'Saldar', 'Salutar', 'Satisfação', 'Segurança', 'Sem defeito', 'Sem igual', 'Sensacional', 'Sério', 'Simpático', 'Simples', 'Singular', 'Sobressaindo-se', 'Solidez', 'Solução', 'Soluciona', 'Solvência', 'Sonho', 'Suave', 'Sucesso', 'Suficiente', 'Superação', 'superprodução', 'Suplantar', 'Talento', 'Ter êxito', 'Término', 'Testemunhar', 'Tolerância', 'Tornar conhecido', 'Trabalhador', 'Tranquilo', 'Transcendente', 'Transparência', 'Triunfo', 'Útil', 'Valioso', 'Vantagem', 'Vencer', 'Ventura', 'Versátil', 'Vibrante', 'Certo', 'Clareza', 'Colaborar', 'Compensação', 'Competência', 'Vontade', 'Esforço', 'Espetacular', 'Estabilidade', 'Estável', 'Estímulo', 'Lisonjeiro', 'Louvável', 'Lucro', 'Mais alto', 'Melhor', 'Recuperação', 'Reestruturar', 'Reintegrar posse', 'Remuneração', 'Rendimento', 'Vigor', 'Vitalidade', 'Vivacidade', 'Vívido', 'Voluntário']

In [ ]:
# Colocar as listas em um dicionário
dicionario_emocoes = {
    "alegria": list_alegria,
    "medo": list_medo,
    "raiva": list_raiva,
    "repugnância": list_repugnancia,
    "surpresa": list_surpresa,
}
print(dicionario_emocoes)

{'alegria': ['Abastança', 'Abono', 'Abrandar', 'Abrilhantar', 'Abundância', 'Acalmar', 'Acessível', 'Aclamado', 'Acolhedor', 'Adiantamento', 'Admirar', 'Afável', 'Completar', 'Compreensível', 'Conceder herança', 'Conciliação', 'Concluir', 'Concordar', 'Condecoração', 'Confiança', 'Congratulação', 'Conquista', 'Consagrado', 'Constância', 'Evolução', 'Excelência', 'Excepcional', 'Excitação', 'Executar', 'Êxito', 'Êxtase', 'Extraordinário', 'Fácil', 'Fantástico', 'Fartura', 'Favorável', 'Merecedor', 'Meritório', 'Momento de alta', 'Muito', 'Notável', 'Notório', 'Obtenção', 'Ocasião propícia', 'Oportunidade', 'Otimista', 'Ótimo', 'Ousadia', 'Rentável', 'Reparação', 'Representação de uma ideia', 'Reputação', 'Resolução', 'Respeito', 'Resultado positivo', 'Retidão', 'Retificação', 'Retribuição', 'Revogação', 'Revolucionar', 'Afirmativo', 'Afortunado', 'Agradável', 'Ajuda', 'Alcançar', 'Alegre', 'Alertar', 'Aliança', 'Alívio', 'Amável', 'Aperfeiçoar', 'Apoiar', 'Aprazível', 'Apreciável', 'Aprimorar', 'Apto', 'Aquisição', 'Aquisição', 'Assegurar', 'Atingir (objetivo)', 'Atitude', 'Atraente', 'Auxílio', 'Avanço', 'Baratear', 'Belo', 'Bem', 'Benéfico', 'Benemérito', 'Benfeitoria', 'Benigno', 'Boa reputação', 'Bom', 'Bondoso', 'Bonito', 'Brilhante', 'Brio', 'Calmo', 'Capaz', 'Caridade', 'Caridoso', 'Categórico', 'Cativante', 'Construtivo', 'Consulta', 'Contente', 'Convicção', 'Convincente', 'Cooperação', 'Cordial', 'Delicioso', 'Descoberta', 'Descobrir', 'Desejável', 'Desempenho superior', 'Desfrutar', 'Despreocupação', 'Destaque', 'Determinação', 'Devidamente', 'Digno', 'Diligente', 'Dinamismo', 'Disciplinar', 'Distinção', 'Diversão', 'Divulgar', 'Duradouro', 'Efetivo', 'Efetuar', 'Eficaz', 'Eficiência', 'Elevar', 'Elogio', 'Emoção', 'Emocionar', 'Empolgado', 'Encantado', 'Encorajar', 'Energético', 'Energia', 'Engrandecer', 'Entreter', 'Entusiasmo', 'Escalar', 'Esclarece', 'Favorito', 'Feliz', 'Fenomenal', 'Fidedigno', 'Fiel/fidelidade', 'Finalizar', 'Firme', 'Firmeza de', 'propósito', 'Folga', 'Força', 'Formidável', 'Formoso', 'Ganhar', 'Garantia', 'Genial', 'Gentil', 'Gracioso', 'Grande', 'Gratificação', 'Hábil', 'Homenagem', 'Honestidade', 'Honorável', 'Honra', 'Ideal', 'Ilustre', 'Imbatível', 'Imperioso', 'Importância', 'Incentivado', 'Incontestável', 'Incrível', 'Indenização', 'Influência', 'Informativo', 'Inovação', 'Instrutivo', 'Integridade', 'Inteireza', 'Intenso', 'Invencível', 'Justificável', 'Líder', 'Ovacionado', 'Parceria', 'Perdoar', 'Perfeição', 'Permissão', 'Perpétuo', 'Perseverança', 'Persistir', 'Perspicaz', 'Plano', 'Plenitude', 'Posicionar', 'Positivo', 'Possibilitar', 'Postura', 'Prazer', 'Preciso', 'Predileto', 'Predisposto', 'Prêmio', 'Prestígio', 'Pretensão', 'Prevenção', 'Proativo', 'Processar', 'Proeza', 'Professar (fé)', 'Proficiência', 'Progresso', 'Promoção cargo)', 'Propício', 'Prosperar', 'Prudência', 'Pulsante', 'Pureza', 'Qualificado', 'Querido', 'Realçar', 'Realização', 'Reaver', 'Receptivo', 'Recompensa', 'Recordação', 'Riqueza', 'Robustez', 'Saldar', 'Salutar', 'Satisfação', 'Segurança', 'Sem defeito', 'Sem igual', 'Sensacional', 'Sério', 'Simpático', 'Simples', 'Singular', 'Sobressaindo-se', 'Solidez', 'Solução', 'Soluciona', 'Solvência', 'Sonho', 'Suave', 'Sucesso', 'Suficiente', 'Superação', 'superprodução', 'Suplantar', 'Talento', 'Ter êxito', 'Término', 'Testemunhar', 'Tolerância', 'Tornar conhecido', 'Trabalhador', 'Tranquilo', 'Transcendente', 'Transparência', 'Triunfo', 'Útil', 'Valioso', 'Vantagem', 'Vencer', 'Ventura', 'Versátil', 'Vibrante', 'Certo', 'Clareza', 'Colaborar', 'Compensação', 'Competência', 'Vontade', 'Esforço', 'Espetacular', 'Estabilidade', 'Estável', 'Estímulo', 'Lisonjeiro', 'Louvável', 'Lucro', 'Mais alto', 'Melhor', 'Recuperação', 'Reestruturar', 'Reintegrar posse', 'Remuneração', 'Rendimento', 'Vigor', 'Vitalidade', 'Vivacidade', 'Vívido', 'Voluntário'], 'medo': ['Abater', 'Acabar', 'Advogar', 'Afetar', 'Aflição', 'Agravar', 'Ameaça', 'Arriscar', 'Assalto', 'Ataque', 'Atrasar', 'Cautela', 'Cercar', 'Coerção', 'Colapso', 'Colisão', 'Colocar em risco', 'Calote', 'Combinação', 'inadequada', 'Condenar', 'Confinar', 'Conspiração', 'Construir algo demasiado grande', 'Contenção', 'Crise', 'Delicado', 'Desconsiderar', 'Desorganizado', 'Desregulado', 'Destituir', 'Detenção', 'Devastar', 'Difícil/Dificuldade', 'Dilema', 'Dirigir mal', 'Disputa', 'Distendido', 'Dívida', 'Dor', 'Dúbio', 'Eliminar', 'Em detrimento de', 'Embaraço', 'Empobrecer', 'Encarcerar', 'Encrenca', 'Enfrentar', 'Entravar', 'Equívoco', 'Escuro', 'Estagnação', 'Gana', 'Hipoteca', 'Hostil', 'Ilegal', 'Imperativo', 'Imprevisível', 'Improbidade', 'Imprudência', 'Inadvertido', 'Inapropriado', 'Incerteza', 'Incitar', 'Inclinado (a fazer algo)', 'Inconfiável', 'Indevido', 'Infração', 'Ingerência', 'Induzir alguém ao', 'Inquérito', 'Inquietação', 'Insalubridade', 'Insolvência', 'Instabilidade', 'Insuficiência', 'Interrogatório', 'Intimação', 'Má fama', 'Malignidade', 'Medo', 'Não estabilizado', 'Não saudável', 'Não segurado', 'Notificação', 'Obscurecer', 'Obstáculo', 'Oculto', 'Ofuscar', 'Oneroso', 'Ônus', 'Ordem Judicial', 'Ordenar (dar ordem)', 'Pânico', 'Paralisação (de', 'atividades)', 'Pavor', 'Perigo', 'Perturbação', 'Precipitado', 'Predatório', 'Preocupação', 'Presidiário', 'Pressionar', 'Receio', 'Recessão', 'Recuo', 'Redução', 'Relutância', 'Repreensão', 'Reprimir', 'Resistência', 'Ressonância', 'Retração', 'Revidar', 'Risco', 'Romper', 'Seguro insuficiente', 'Sem documento', 'Sem garantia', 'Sem seguro', 'Severo', 'Sofrer', 'Sombrio', 'Substituir', 'Superestimar', 'Suscetível', 'Temor', 'Derrota', 'Derrubar', 'Desabrigar', 'Desalojar', 'Descapacitar-se', 'Descapitalizado', 'Desconhecer', 'Explosão', 'Extremo', 'Fechar', 'Flagrante', 'Frágil', 'Fratura', 'Fuga', 'Intimidar', 'Inversão', 'Inviável', 'Lesionar', 'Levar aos tribunais', 'Litígio', 'Prisão', 'Processos Inconclusivos', 'Proibição', 'Punição', 'Questionável', 'Tensão', 'Terror', 'Tropeço', 'Turbulência', 'Urgência'], 'raiva': ['Afronta', 'Aborrecer', 'Acusação', 'Administração', 'danosa', 'Antiético', 'Apontado', 'erroneamente', 'Atormentar', 'Atrapalhar', 'Avaliação', 'incorreta do preço', 'Avaliar mal', 'Aviltamento', 'Boicote', 'Caiu', 'Atroz', 'Calúnia', 'Carga', 'Censura', 'Coação', 'Combater', 'Complicar', 'Confrontar', 'Depredar', 'Desacato', 'Desaceleração', 'Desatenção', 'Desavença', 'Desdém', 'Desentendimento', 'Desequilíbrio', 'Desfigurar', 'Desistência', 'Destruir', 'Detrair', 'Difamar', 'Discordar', 'Desviar', 'Dissimulação', 'Dissuadir', 'Distorção', 'Empecilho', 'Empregar indevidamente', 'Encurralar', 'Gargalo', 'Grosseiro', 'Ilegível', 'Implicar', 'Importunar', 'Imposto', 'Inaceitável', 'Inadimplência', 'Inadmissível', 'Incoerência', 'Inconveniência', 'Incorreto', 'Má fé', 'erro', 'Ineficácia', 'Infligido', 'Informação errada', 'Informar mal', 'Infundado', 'Injustiça', 'Inoportuno', 'Insistência', 'Juízo equivocado', 'Julgamento invalido', 'Julgar mal', 'Letargia', 'Limitação', 'Má aplicação', 'Má classificação', 'Mal aplicado', 'Mal dirigido', 'Mal pago', 'Mal rotulado', 'Maldade', 'Manipular', 'Mau', 'Minimizar o valor (a', 'importância)', 'Moralmente ofensivo', 'Morosidade', 'Multa', 'Não amigável', 'Não executado', 'Não pago', 'Oportunista', 'Opulência', 'Pago em excesso', 'Pane', 'Penalidade', 'Pendência', 'Perjúrio', 'Perseguir', 'Preço abusivo', 'Preconceito', 'Propina', 'Reembolso', 'Relatar', 'erroneamente', 'Remarcação de', 'preços', 'Represália', 'Retaliação', 'Ríspido', 'Roubo', 'Sabotagem', 'Servidão forçada', 'Tentativa de', 'agressão', 'Contradizer', 'Controvérsia', 'Crime', 'Delito', 'Delongar', 'Denegrir', 'Vítima', 'Enganar', 'Exploração', 'Fazer pouco caso', 'Fazer vista grossa', 'Fixação errônea de', 'preço', 'Furioso', 'Insubordinação', 'Intriga', 'Invasão', 'Inverdade', 'Irresponsável', 'Irritação', 'Não planejado', 'Obstrução', 'Obtenção de', 'vantagem sobre algo', 'Ódio', 'Omissão', 'Operação tartaruga', 'Traição', 'Trama ou acordo', 'secreto', 'Transgredir', 'Trapaça', 'Uso incorreto', 'Vagaroso'], 'repugnância': ['Admoestação', 'Abusar', 'Adulterar', 'Afirmar', 'erroneamente', 'Agiotagem', 'Alongar', 'Anticoncorrencial', 'Antieconômico', 'Antiquado', 'Aperto', 'Apodrecido', 'Aporrinhar', 'Assimetria', 'Ato Condenável', 'Classificação Errônea', 'Avaria', 'Beligerante', 'Burlar', 'Castigado', 'Clandestino', 'Conduta ilegal', 'Contaminar', 'Contravenção', 'Depravado', 'Depreciativo', 'Desagradável', 'Desatualizado', 'Descrédito', 'Desgraça', 'Desleal', 'Desmentido', 'Desonesto', 'Despeito', 'Desrespeitar', 'Desvalorizar', 'Inesperado', 'Devasso', 'Discórdia', 'Embaçado', 'Escândalo', 'Estorvar', 'Exacerbar', 'Falsidade', 'Fingir', 'Fraude', 'Fútil', 'Ignorante', 'Ilícito', 'Imoral', 'Imperícia', 'Inábil', 'Indecência', 'Indignidade', 'Ineficiência', 'Inexatidão', 'Infiltrar-se', 'Insulto', 'Intencional', 'Intrusão', 'Irregularidade', 'Lavagem de dinheiro', 'Lesar', 'Repentino', 'Maleficência', 'Malefício', 'Malícia', 'Maquiar resultados, balanços', 'Medíocre', 'Menosprezar', 'Mentira', 'Mesquinhez', 'Minar', 'Molestar', 'Não confiável', 'Não moral', 'Negligência', 'Nocivo', 'Nojento', 'Objeção', 'Obsceno', 'Ofertado em excesso', 'Paga mal', 'Pervasivo', 'Perverso', 'Peso morto', 'Pichação', 'Prevaricação', 'Provocar', 'Quadrilha', 'Repelir', 'Repúdio', 'Repugnante', 'Repulsa', 'Ridículo', 'Saquear', 'Sem validade legal', 'Subfinanciado', 'Subjugação', 'Suborno', 'Temperamental', 'Tirar vantagem', 'Tumulto', 'Ultraje', 'Usurpar', 'Vandalismo', 'Vingança', 'Violar', 'Violência', 'Vomitar'], 'surpresa': ['Acaso', 'Acionar', 'Agarrar', 'Alegar', 'Antecipação', 'Argumentar', 'Atencioso', 'Atrito', 'Aumentar', 'Aviso', 'Brusco', 'Choque', 'Citação', 'Judicial', 'Falta', 'Confessar', 'Contrapor', 'Contratempo', 'Desaguar', 'Desavisado', 'Deslize', 'Desmedido', 'Desnudo', 'Digressão', 'Disparidade', 'Distração', 'Egrégio', 'Façanha', 'Hesitação', 'Ilógico', 'Inacessível', 'Inacreditável', 'Incontrolável', 'Anticompetitivo', 'Inexorável', 'Inigualável', 'Insuperável', 'Justificativa parcial', 'Mistério', 'Modificar', 'radicalmente', 'Não agendado', 'Não anunciado', 'Não contabilizado', 'Não previsto', 'Não receptivo', 'Não revelado', 'Novidade', 'Perplexo', 'Pior (que)', 'Pleitear', 'Posto no lugar errado', 'Precoce', 'Protesto', 'Readquirir', 'Reavaliação', 'Recusar', 'Desafortunado', 'Revelação', 'Reverberância', 'Reversão de pena ou sentença', 'Reviravolta', 'Revisão', 'Saída ou exclusão', 'de ações', 'Segredo', 'Situação sem saída', 'Súbito', 'Superproduz', 'Suspeito', 'Travessura', 'Vencido', 'Volátil']}

### Preparar df (relatórios)

In [ ]:
# Limpar valores NaN e garantir que tudo seja string
df['t-1'] = df['t-1'].fillna("").astype(str)
df['t'] = df['t'].fillna("").astype(str)
df['t+2'] = df['t+2'].fillna("").astype(str)

# Funções

## Função: Contagem das categorias

In [ ]:
# Contagem das categorias de cada coluna
def contagem_classes(df, cols):
  ''' Função que faz a contagem de classes de cada coluna
      Args:
        - df: dataframe com as colunas a serem contadas
        - cols: lista com os nomes das colunas
  '''

  # Criar um dicionário vazio para armaezar os dados
  result = {}
  # Loop para : Contagem de valores de cada categoria
  for col in cols:
    result[col]= df[col].value_counts()

  # Tranformar o dicionário em DataFrame e fazer sua Transposição
  df_result = pd.DataFrame(result)#.T
  # Substituir NA por 0. E, converter todas as contagens para 'int64'
  df_result = df_result.fillna(0).astype('int64')
  return df_result

 # Modelo 1: Só com único relatório
 Este é um modelo teste, só rodei com um único relatório para testar. O código final está no modelo 2.

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Modelo pré-treinado (aceita textos em português)
modelo_sbert = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# O dicionário é codificado pelo modelo SBERT para gerar seu embedding
embeddings_emocoes = {emocao: modelo_sbert.encode(" ".join(map(str, lista))) for emocao, lista in dicionario_emocoes.items()}
# Para cada emoção no dicionario_emocoes, as palavras associadas a ela são unidas em uma única string
#  com " ".join(map(str, lista)) e, em seguida, o modelo gera o embedding dessa string.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.89k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# Exibir embeddings do dicionário de emoções
for chave, valor in embeddings_emocoes.items():
    print(f"{chave}: {valor[:5]}")  # Exibir os primeiros números de cada lista de valores

alegria: [ 0.08052162  0.2852479   0.11884767  0.03268695 -0.19898008]
medo: [0.12895432 0.1503499  0.05885961 0.13182724 0.0835663 ]
raiva: [ 0.09908537  0.13059825 -0.02357616  0.05435435  0.16301349]
repugnância: [ 0.13294192  0.21273977 -0.02310401  0.06294704  0.0630016 ]
surpresa: [ 0.10175819  0.14125508 -0.1068872   0.04164942  0.07206219]

In [ ]:
# Pegando só um relatório
texto = df['t-1'][0]
texto

'A Petróleo Brasileiro S.A.  Petrobras dedicase, diretamente ou por meio de suas subsidiárias e controladas (denominadas, em conjunto, “Petrobras” ou a “Companhia”), à pesquisa, lavra, refino, processamento, comércio e transporte de petróleo proveniente de poço, de xisto ou de outras rochas, de seus derivados, de gás natural e de outros hidrocarbonetos fluidos, além das atividades vinculadas à energia, podendo promover pesquisa, desenvolvimento, produção, transporte, distribuição e comercialização de todas as formas de energia, bem como quaisquer outras atividades correlatas ou afins. A sede social da Companhia está localizada no Rio de Janeiro  RJ.\nAs demonstrações contábeis incluem:\n As demonstrações contábeis consolidadas estão sendo apresentadas de acordo com os padrões internacionais de demonstrações contábeis (IFRS) emitidos pelo International Accounting Standards Board  IASB e também de acordo com práticas contábeis adotadas no Brasil.\n As demonstrações contábeis individuais estão sendo apresentadas de acordo com as práticas contábeis adotadas no Brasil, em observância às disposições contidas na Lei das Sociedades por Ações, e incorporam as mudanças introduzidas por intermédio das Leis 11.638/07 e 11.941/09, complementadas pelos pronunciamentos, interpretações e orientações do Comitê de Pronunciamentos Contábeis  CPC, aprovados por resoluções do Conselho Federal de Contabilidade  CFC e por normas da Comissão de Valores Mobiliários  CVM.\n Os pronunciamentos, interpretações e orientações do CPC estão convergentes às normas internacionais de contabilidade emitidas pelo IASB. Dessa forma, as demonstrações contábeis individuais não apresentam diferenças em relação às consolidadas em IFRS, exceto pela manutenção do ativo diferido, conforme previsto no CPC 43 (R1), aprovado pela Deliberação CVM 651/10. As reconciliações do patrimônio líquido e resultado da controladora com o consolidado estão na nota explicativa 3.1.1.\nAs demonstrações contábeis foram preparadas utilizando o custo histórico como base de valor, exceto para os ativos financeiros disponíveis para venda, ativos e passivos financeiros mensurados ao justo valor e determinadas classes de ativos e passivos circulantes e não circulantes, conforme apresentado na nota explicativa de políticas contábeis.\nO Conselho de Administração da Companhia, em reunião realizada em 25 de fevereiro de 2014, autorizou a divulgação destas demonstrações contábeis.\nAs demonstrações do valor adicionado  DVA apresentam informações relativas à riqueza criada pela Companhia e a forma como tais riquezas foram distribuídas. Essas demonstrações foram preparadas de acordo com o CPC 09\n Demonstração do Valor Adicionado, aprovado pela Deliberação CVM 557/08 e para fins de IFRS são apresentadas como informação adicional.\n\nA moeda funcional da Petrobras e de suas controladas no Brasil é o real. A moeda funcional da maior parte das controladas que atuam em ambiente econômico internacional é o dólar norteamericano. A Petrobras Argentina\nS.A. tem o peso argentino como moeda funcional.\nAs demonstrações do resultado e do fluxo de caixa das investidas, que atuam em ambiente econômico estável com moeda funcional distinta da Controladora são convertidas para reais pela taxa de câmbio média mensal, os ativos e passivos são convertidos pela taxa final e os demais itens do patrimônio líquido são convertidos pela taxa histórica.\nAs variações cambiais sobre os investimentos em controladas e coligadas, com moeda funcional distinta da Controladora, são registradas no patrimônio líquido, como ajuste acumulado de conversão, sendo transferidas para o resultado quando da realização dos investimentos.\nAs Demonstrações Contábeis em 31 de dezembro de 2012 e em 1º de janeiro de 2012 estão sendo reapresentadas para fins comparativos, contemplando os seguintes efeitos:\nEm 2013 entrou em vigor a revisão do IASB sobre a norma IAS 19  Benefícios a Empregados (CPC 33 – R1), que eliminou a possibilidade do diferimento das perdas/ganhos atuariais dos planos de pensão e saúde (método corredor) e requer o cálculo dos juros líquidos com base na aplicação da taxa de desconto sobre o saldo dos passivos líquidos de ativos do plano.\nEm decorrência desta alteração a Companhia reconheceu em suas demonstrações contábeis consolidadas do exercício findo em 31 de dezembro de 2012 um aumento do passivo atuarial líquido em R$ 20.764 (R$ 11.590 em 1º de janeiro de 2012), tendo como contrapartida uma redução do passivo fiscal diferido de R$ 6.105 (R$ 3.108 em 1º de janeiro de 2012) e do patrimônio líquido de R$ 14.659 (R$ 8.482 em 1º de janeiro de 2012).\nA companhia passou a apresentar o imposto de renda e contribuição social diferidos em base líquida no ativo ou no passivo, considerando os saldos de cada uma das empresas consolidadas, refletindo na redução de R$ 8.978 no ativo e no passivo consolidados (redução de R$ 6.714 em 1º de janeiro de 2012).\nA seguir são apresentados os efeitos das reclassificações para comparabilidade nos itens do balanço patrimonial:\n  Divulgado nas demonstrações contábeis do exercício findo em 31 de dezembro de 2012.\n\n\nEstas alterações não geraram impactos materiais aos resultados e aos fluxos de caixa da Companhia.\nAs práticas contábeis descritas abaixo foram aplicadas de maneira consistente pela Companhia nas demonstrações contábeis apresentadas.\nAs demonstrações contábeis consolidadas abrangem informações da Petrobras e das suas controladas. O controle é obtido quando a Petrobras possui: i) poder sobre a investida; ii) exposição a, ou direitos sobre, retornos variáveis decorrentes de seu envolvimento com a investida; e iii) a capacidade de utilizar seu poder sobre a investida para afetar o valor de seus retornos.\nSubsidiárias e controladas são consolidadas a partir da data em que o controle é obtido até a data em que esse controle deixa de existir, utilizando práticas contábeis consistentes às adotadas pela Companhia.\nO processo de consolidação das contas patrimoniais e de resultado corresponde à soma dos saldos das contas de ativo, passivo, receitas e despesas, segundo a sua função, complementada com as eliminações das operações realizadas entre empresas consolidadas, bem como dos saldos e resultados não realizados economicamente entre as referidas empresas.\nAs empresas consolidadas sãs as seguintes:\n\n\n\n\n Empresas sediadas no exterior com demonstrações contábeis elaboradas em moeda estrangeira.\n\nA Petrobras não tem participação acionária nas entidades estruturadas consolidadas, no entanto, o controle é determinado pelo poder que a Companhia possui sobre as atividades operacionais relevantes dessas entidades.\n Reapresentado em decorrência da revisão do IAS19  Benefícios a empregados (CPC33  R1), conforme nota explicativa 2.3.\n\n\nAs informações contábeis por segmento operacional (área de negócio) da Companhia são elaboradas com base em itens atribuíveis diretamente ao segmento, bem como aqueles que podem ser alocados em bases razoáveis.\nNa apuração dos resultados segmentados são consideradas as transações realizadas com terceiros e as transferências entre as áreas de negócio, sendo estas valoradas por preços internos de transferência definidos entre as áreas e com metodologias de apuração baseadas em parâmetros de mercado.\nAs informações por área de negócio na Companhia estão segmentadas de acordo com o modelo de organização vigente, contendo as seguintes áreas:\nExploração e Produção (E&P): abrange as atividades de exploração, desenvolvimento da produção e produção de petróleo, LGN (líquido de gás natural) e gás natural no Brasil, objetivando atender, prioritariamente, as refinarias do país e, ainda, comercializando nos mercados interno e externo o excedente de petróleo, bem como derivados produzidos em suas plantas de processamento de gás natural, atuando, também, de forma associada com outras empresas em parcerias.\nAbastecimento: contempla as atividades de refino, logística, transporte e comercialização de derivados e petróleo, exportação de etanol, extração e processamento de xisto, além das participações em empresas do setor petroquímico no Brasil.\n\n\nGás e Energia: engloba as atividades de transporte e comercialização do gás natural produzido no país ou importado, de transporte e comercialização de GNL, de geração e comercialização de energia elétrica, assim como as participações societárias em transportadoras e distribuidoras de gás natural e em termoelétricas no Brasil, além de ser responsável pelos negócios com fertilizantes.\n\nBiocombustível: contempla as atividades de produção de biodiesel e seus coprodutos e as atividades de etanol, através de participações acionárias, da produção e da comercialização de etanol, açúcar e o excedente de energia elétrica gerado a partir do bagaço da canadeaçúcar.\n\nDistribuição: responsável pela distribuição de derivados, etanol e gás natural veicular no Brasil, representada principalmente pelas operações da Petrobras Distribuidora.\n\nInternacional: abrange as atividades de exploração e produção de petróleo e gás, de abastecimento, de gás e energia e de distribuição, realizadas no exterior, em diversos países das Américas, África, Europa e Ásia.\nNo grupo de órgãos corporativos são alocados os itens que não podem ser atribuídos às demais áreas, notadamente aqueles vinculados à gestão financeira corporativa, o overhead relativo à Administração Central e outras despesas, inclusive as atuariais referentes aos planos de pensão e de saúde destinados aos aposentados e beneficiários.\nIncluem numerário em espécie, depósitos bancários disponíveis e aplicações financeiras de curto prazo com alta liquidez, vencíveis em até três meses, contados da data da contratação original, prontamente conversíveis em um montante conhecido de caixa e com risco insignificante de mudança de valor.\nInvestimentos em títulos e valores mobiliários compreendem investimentos em títulos de dívida e patrimônio. Estes instrumentos são inicialmente mensurados ao valor justo e são classificados e mensurados subsequentemente conforme abaixo:\n Valor justo por meio do resultado: Incluem títulos adquiridos ou incorridos principalmente para a finalidade de venda ou de recompra em prazo muito curto. São mensurados subsequentemente à aquisição ao valor justo. Alterações no valor justo são reconhecidas no resultado.\n Mantidos até o vencimento: Incluem títulos não derivativos com pagamentos fixos ou determináveis com vencimentos definidos para os quais a Companhia tem intenção e capacidade de manter até o vencimento. São mensurados subsequentemente à aquisição pelo custo amortizado, utilizando o método da taxa de juros efetiva.\n Disponíveis para venda: Incluem títulos não derivativos que são designados como disponíveis para venda ou que não são classificados como investimentos mantidos até o vencimento ou pelo valor justo por meio do resultado. São mensurados subsequentemente ao valor justo. Alterações no valor justo são reconhecidas em outros resultados abrangentes, no patrimônio líquido, e reclassificadas para resultado quando o instrumento é desreconhecido.\nAlterações posteriores atribuíveis a juros, variação cambial e inflação são reconhecidas no resultado para todas as categorias, quando aplicáveis.\n\nSão contabilizados inicialmente pelo valor justo da contraprestação a ser recebida e, subsequentemente, mensurados pelo custo amortizado, com o uso do método da taxa de juros efetiva, sendo deduzidas as perdas por redução ao valor recuperável de ativos (impairment) e crédito de liquidação duvidosa.\nA Companhia reconhece as perdas em créditos de liquidação duvidosa quando existe evidência objetiva de perda no valor recuperável, como resultado de um ou mais eventos que ocorreram após o reconhecimento inicial do ativo, que impactam os fluxos de caixa futuros estimados e que possam ser confiavelmente estimadas. Evidências de perdas incluem: casos de dificuldades financeiras significativas e probabilidade significativa do cliente entrar com pedido de falência ou recuperação judicial.\nSão reconhecidos pelo valor justo menos os custos de transação incorridos e, após o reconhecimento inicial, são mensurados pelo custo amortizado utilizandose do método da taxa de juros efetiva.\nInstrumentos financeiros derivativos são reconhecidos como ativos ou passivos no balanço patrimonial e mensurados inicialmente e subsequentemente ao valor justo.\nGanhos ou perdas resultantes das alterações no valor justo são reconhecidas no resultado financeiro, exceto quando o derivativo é qualificado e designado para contabilidade de hedge (hedge accounting).\nNo início da contabilidade de hedge, a Companhia elabora documentação formal da relação de hedge e do objetivo e estratégia da gestão de risco.\nAs relações de hedge que se qualificam como hedge accounting são:  hedge de valor justo, quando se refere a hedge de exposição às alterações no valor justo de ativo ou passivo reconhecido ou de compromisso firme não reconhecido, ou de parte identificada de tal ativo, passivo ou compromisso firme; e  hedge de fluxos de caixa, quando se refere a hedge de exposição à variabilidade nos fluxos de caixa que seja atribuível a um risco particular associado a um ativo ou passivo reconhecido ou a uma transação prevista altamente provável.\nNas operações envolvendo instrumentos financeiros derivativos designados e qualificados como hedge de valor justo, os ganhos ou perdas resultantes da mensuração ao valor justo do instrumento e do objeto de hedge são reconhecidos no resultado.\nPara hedges qualificados como de fluxo de caixa, a Companhia designa instrumentos financeiros derivativos e nãoderivativos, sendo a parcela efetiva dos ganhos e perdas decorrentes das variações do valor justo reconhecida no patrimônio líquido e transferida para o resultado quando o item protegido for efetivamente realizado. A parcela não efetiva do hedge é registrada no resultado do período.\nQuando um instrumento de hedge vence ou é liquidado antecipadamente, quando um hedge não atende mais aos critérios de contabilização de hedge ou quando a Administração decide revogar a designação de hedge accounting, o ganho ou perda acumulado permanece reconhecido no patrimônio. A reclassificação do ganho ou perda para o resultado é realizada quando a transação prevista ocorre. Quando não se espera mais que uma operação prevista ocorra, o ganho ou a perda acumulado no patrimônio é imediatamente transferido para a demonstração do resultado.\n\nOs estoques são mensurados pelo seu custo médio ponderado de aquisição ou de produção e compreende, principalmente, petróleo bruto, intermediários e derivados de petróleo, assim como gás natural e gás natural liquefeito (GNL), fertilizantes e biocombustíveis, ajustados, quando aplicável, ao seu valor de realização líquido.\nOs estoques de petróleo e gás natural liquefeito (GNL) podem ser comercializados em estado bruto, assim como consumidos no processo de produção de seus derivados e/ou utilizados para geração de energia, respectivamente.\nOs intermediários são formados por correntes de produtos que já passaram por pelo menos uma unidade de processamento, mas ainda necessitam ser processados, tratados ou convertidos para serem disponibilizados para venda.\nOs biocombustíveis compreendem, principalmente, os saldos de estoques de etanol e biodiesel.\nMateriais e suprimentos para manutenção e outros representam, principalmente, insumos de produção e materiais de operação e consumo que serão utilizados nas atividades da Companhia, exceto matériasprimas, e estão demonstrados ao custo médio de compra, que não excede ao de reposição.\nO valor de realização líquido compreende o preço de venda estimado no curso normal dos negócios, menos os custos estimados de conclusão e aqueles necessários para a realização da venda.\nOs estoques incluem as importações em andamento, que são demonstradas ao custo identificado.\nColigada é a entidade sobre a qual a Companhia possui influência significativa, definida como o poder de participar das decisões sobre políticas financeiras e operacionais de uma investida, mas sem que haja o controle individual ou conjunto dessas políticas.\nEm um negócio em conjunto duas ou mais partes têm o controle conjunto, podendo ser uma operação em conjunto ou um empreendimento controlado em conjunto, dependendo dos direitos e obrigações das partes.\nEnquanto em uma operação em conjunto, as partes integrantes têm direitos sobre os ativos e obrigações sobre os passivos relacionados ao negócio, em um empreendimento controlado em conjunto, as partes têm direitos sobre os ativos líquidos do negócio.\nOs resultados e os ativos e passivos das coligadas e dos empreendimentos controlados em conjunto são reconhecidos pelo método de equivalência patrimonial.\nA companhia reconhece a totalidade dos seus ativos, passivos e as respectivas receitas e despesas nas operações controladas em conjunto. Adicionalmente, reconhece a sua parcela nas receitas e despesas, bem como dos ativos e passivos detidos em conjunto.\nNas demonstrações individuais os investimentos em empresas controladas são reconhecidos pelo método de equivalência patrimonial. A definição de controle é apresentada na nota explicativa 3.1.\n\nAquisições de negócios são reconhecidas pelo método da aquisição quando o controle é obtido. Transações envolvendo empresas sob controle comum não configuram uma combinação de negócios.\n\n\nO referido método requer que os ativos identificáveis adquiridos e os passivos assumidos sejam mensurados pelo seu valor justo. O montante pago, acima desse valor deve ser reconhecido como ágio por expectativa de rentabilidade futura (goodwill). Quando o custo de aquisição for menor que o valor justo dos ativos líquidos adquiridos, um ganho proveniente de compra vantajosa é reconhecido no resultado.\nAs mudanças de participações em controladas que não resultem em perda de controle são reconhecidas diretamente no patrimônio líquido, como contribuição adicional de capital, pela diferença entre o preço pago/recebido e o valor contábil da participação adquirida/vendida.\nNas aquisições de participação em coligadas e empreendimentos controlados em conjunto, sem a obtenção de controle, apesar de não configurarem uma combinação de negócios, o goodwill é mensurado pelo excesso do custo de aquisição sobre os ativos líquidos adquiridos e é apresentado no investimento.\nOs gastos incorridos com exploração e desenvolvimento da produção de petróleo e gás natural são contabilizados de acordo com o método dos esforços bem sucedidos, que considera as seguintes características gerais:\n Gastos relacionados com atividades de geologia e geofísica são reconhecidos como despesas no período em que são incorridos.\n Valores relacionados à obtenção de direitos e concessões para exploração de petróleo e gás natural natural são inicialmente capitalizados.\n Custos exploratórios diretamente associados à perfuração de poços são inicialmente capitalizados no ativo imobilizado até que sejam constatadas ou não reservas provadas relativas ao poço. Os custos posteriores à perfuração do poço continuam a ser capitalizados desde que o volume de reservas descobertos justifique o seu reconhecimento futuro como poço produtor e estudos das reservas e da viabilidade econômica e operacional do empreendimento estiverem em curso. Uma comissão interna de executivos técnicos da Petrobras revisa mensalmente as condições de cada poço, levandose em consideração os dados de geologia, geofísica e engenharia, condições econômicas, métodos operacionais e regulamentações governamentais.\n Poços exploratórios secos ou sem viabilidade econômica e os demais custos vinculados às reservas não comerciais são reconhecidos como despesa no período, quando identificados como tal.\n Construção, instalação e conclusão de infraestrutura, tais como plataformas, dutos, perfuração de poços de desenvolvimento e outros custos relacionados ao desenvolvimento de reservas provadas e eco

In [ ]:
# O texto do relatório é codificado pelo modelo SBERT para gerar seu embedding.
embedding_texto = modelo_sbert.encode(texto)
embedding_texto[:30] # Exibir os primeiros valores

array([ 0.01755016, -0.13767509, -0.03087044, -0.03717567, -0.0446121 ,
       -0.23386687,  0.00959395,  0.27701497,  0.13821588, -0.07641162,
        0.00738324,  0.09215353, -0.19796437, -0.03552497, -0.23027293,
       -0.20190232,  0.07182094, -0.27487418,  0.32575488, -0.01352627,
        0.45432383, -0.04644673, -0.16989584, -0.01763631, -0.38970712,
        0.3518448 , -0.15578893,  0.02300895,  0.12211439, -0.289873  ],
      dtype=float32)

In [ ]:
# Calcular similaridade entre o texto e cada emoção
similaridades = {
    emocao: cosine_similarity([embedding_texto], [embedding])[0][0]
    for emocao, embedding in embeddings_emocoes.items()
}

# Exibir resultados ordenados
df_similaridades = pd.DataFrame(similaridades.items(), columns=['Emoção', 'Similaridade'])
df_similaridades = df_similaridades.sort_values(by='Similaridade', ascending=False)
print(df_similaridades)

        Emoção  Similaridade
2        raiva      0.168656
3  repugnância      0.136497
1         medo      0.105753
0      alegria      0.070319
4     surpresa      0.029384

# Modelo 2: Usando toda a tabela

Esse é o código final

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Modelo pré-treinado (aceita textos em português)
modelo_sbert = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# O dicionário é codificado pelo modelo SBERT para gerar seu embedding
embeddings_emocoes = {emocao: modelo_sbert.encode(" ".join(map(str, lista))) for emocao, lista in dicionario_emocoes.items()}
# Para cada emoção no dicionario_emocoes, as palavras associadas a ela são unidas em uma única string
#  com " ".join(map(str, lista)) e, em seguida, o modelo gera o embedding dessa string.

In [ ]:
def calcular_similaridades(linha, t):
    texto = str(linha[t]) if pd.notna(linha[t]) else ""
    # O texto do relatório é codificado pelo modelo SBERT para gerar seu embedding.
    embedding_texto = modelo_sbert.encode(texto)

    # Calcular as similaridades
    similaridades = {
        emocao: cosine_similarity([embedding_texto], [embedding])[0][0]
        for emocao, embedding in embeddings_emocoes.items()
    }


    # Determinar o sentimento predominante
    sentimentos = {key: value for key, value in similaridades.items()}
    similaridades[f'Sentimento_{t}'] = max(sentimentos, key=sentimentos.get)  # Determinar a emoção predominante

    return similaridades

# Aplicar a função em todas as linhas
df_tf_t1 = pd.DataFrame(df.apply(lambda linha: calcular_similaridades(linha, t='t-1'), axis=1).tolist())
df_tf_t = pd.DataFrame(df.apply(lambda linha: calcular_similaridades(linha, t='t'), axis=1).tolist())
df_tf_t2 = pd.DataFrame(df.apply(lambda linha: calcular_similaridades(linha, t='t+2'), axis=1).tolist())

# Concatenar as tabelas
df_resultados_tf1 = pd.concat([df_tf_t1[['Sentimento_t-1']], df_tf_t[['Sentimento_t']], df_tf_t2[['Sentimento_t+2']]], axis=1)
# Exibir os resultados
df_resultados_tf1.head()

  Sentimento_t-1 Sentimento_t Sentimento_t+2
0          raiva        raiva          raiva
1          raiva        raiva          raiva
2    repugnância  repugnância          raiva
3    repugnância  repugnância          raiva
4          raiva        raiva          raiva

In [ ]:
# Aplicar a função para calcular a contagem
cols = ['Sentimento_t-1','Sentimento_t','Sentimento_t+2']
df_cont1 = contagem_classes(df_resultados_tf1, cols)
df_cont1

             Sentimento_t-1  Sentimento_t  Sentimento_t+2
medo                      9             7               9
raiva                    19            18              16
repugnância              22            25              24
surpresa                  0             0               1